name: ci-documentation 

on: 
    push: 
        branches: [ main ]
    pull_request:
        branches: [ main ]

permissions:
    contents: read 
    pages: write 
    id-token: write 

concurrency:
    group: "pages"
    cancel-in-progress: false 

jobs:

    docs:
        runs-on: ubuntu-latest 
        timeout-minutes: 15 
        steps:
            - name: Checkout Repo 
              uses: actions/checkout@v4 
            
            - name: Setup Python 
              uses: actions/setup-python@v5 
              with:
                python-version: "3.12"

            - name: Install requirements 
              run: | 
                python -m pip install --upgrade pip 
                pip install .[docs]

            - name: Build the docs 
              run: sphinx-build -b html docs/source docs/build/html 

            - name: Setup Pages 
              if: ${{ github.event_name == 'push' }}
              uses: actions/configure-pages@v5 

            - name: Upload Docs 
              if: ${{ github.event_name == 'push' }}
              uses: actions/upload-pages-artifact@v3 
              with: 
                path: ./docs/build/html 

            - name: Deploy to GitHub Pages 
              if: ${{ github.event_name == 'push' }}
              id: deployment 
              uses: actions/deploy-pages@v4 